[package]
name = "cold-bitcoin-wallet"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.38", features = ["derive"] }
k256 = { version = "0.13.4", features = ["arithmetic"] }
serde_json = "1.0.140"
sha2 = "0.10.9"
thiserror = "2.0.12"

[dev-dependencies]
rstest = "0.25.0"
